
#pragma once

// default layer count
#define DYNAMIC_KEYMAP_LAYER_COUNT 14

#define ENCODER_RESOLUTION 4
#define ENCODER_RESOLUTION_RIGHT 4
#define MOUSEKEY_INITIAL_SPEED 2000
#define MK_3_SPEED
// #define MK_MOMENTARY_ACCEL
